### ISSUE TITLE
Microocpp initialize but not connecting to websocket server (SteVe) over sim800c

### ISSUE THREAD

**Issue by FlxMojojojo** [ziyadtarek7/Using-MicroOCPP-with-SIM800-Module#1]
Hi @ziyadtarek7 I'm trying to connect to the WebSocket Server (SteVe) from the device, everyting is fine until the Microcopp initialize, after that, I can't see it is connected to the Websocket URL which is usually prints on serial monitor when it is connected to the server. Also I don't see the device ID available in SteVe. I am adding the serial log for the reference, if you could help me to solve this it would be really helpful.. 

21:43:12.083 -> [SUCCESS]
21:43:12.083 -> Connecting to APN:      | airtelgprs.com
21:43:12.083 -> GPRS Connect Status:    |[SUCCESS]
21:43:19.044 -> Operator:               |Airtel
21:43:19.091 -> Local IP:               |10.12.59.236
21:43:19.137 -> Signal quality:         |25
21:43:19.137 -> SIM Number:         |*********************** // sim number is replaced here with *
21:43:19.510 -> -------------------------------------------------------
21:43:19.510 -> Initializing modem...
21:43:19.697 -> Modem Info: SIM800 R14.18
21:43:19.697 -> Connecting to airtelgprs.com success
21:43:23.902 -> GPRS connected
21:43:23.902 -> [MO] info (MicroOcpp.cpp:131): connecting to ws://20.185.250.105:8080/steve/websocket/CentralSystemService/FLX_HDINGSM -- (host: 20.185.250.105, port: 8080)
21:43:23.948 -> [MO] debug (FilesystemAdapter.cpp:74): LittleFS mount success
21:43:23.948 -> [MO] debug (MicroOcpp.cpp:202): initialize OCPP
21:43:23.948 -> [MO] debug (MicroOcpp.cpp:205): filesystem loaded
21:43:23.995 -> [MO] debug (FilesystemAdapter.cpp:143): File open successful: /bootstats.jsn
21:43:23.995 -> [MO] debug (FilesystemUtils.cpp:73): Loaded JSON file: /bootstats.jsn
21:43:24.134 -> [MO] debug (FilesystemAdapter.cpp:143): File open successful: /bootstats.jsn
21:43:24.134 -> [MO] debug (FilesystemUtils.cpp:114): Wrote JSON file: /bootstats.jsn
21:43:24.134 -> [MO] debug (Configuration.cpp:70): init new configurations container: /opstore.jsn
21:43:24.181 -> [MO] debug (FilesystemAdapter.cpp:143): File open successful: /opstore.jsn
21:43:24.181 -> [MO] debug (FilesystemUtils.cpp:73): Loaded JSON file: /opstore.jsn
21:43:24.181 -> [MO] debug (ConfigurationContainerFlash.cpp:190): Initialization finished
21:43:24.226 -> [MO] debug (RequestStore.cpp:121): operation 0 does not exist
21:43:24.226 -> [MO] debug (RequestStore.cpp:121): operation 1 does not exist
21:43:24.226 -> [MO] debug (RequestStore.cpp:121): operation 2 does not exist
21:43:24.226 -> [MO] debug (Configuration.cpp:70): init new configurations container: /txstore.jsn
21:43:24.226 -> [MO] debug (FilesystemAdapter.cpp:143): File open successful: /txstore.jsn
21:43:24.273 -> [MO] debug (FilesystemUtils.cpp:73): Loaded JSON file: /txstore.jsn
21:43:24.273 -> [MO] debug (ConfigurationContainerFlash.cpp:190): Initialization finished
21:43:24.273 -> [MO] debug (Configuration.cpp:70): init new configurations container: /ocpp-config.jsn
21:43:24.273 -> [MO] debug (OperationRegistry.cpp:40): registered operation BootNotification
21:43:24.273 -> [MO] debug (Configuration.cpp:70): init new configurations container: /volatile
21:43:24.273 -> [MO] debug (OperationRegistry.cpp:40): registered operation ChangeAvailability
21:43:24.273 -> [MO] debug (OperationRegistry.cpp:40): registered operation ChangeConfiguration
21:43:24.319 -> [MO] debug (OperationRegistry.cpp:40): registered operation ClearCache
21:43:24.319 -> [MO] debug (OperationRegistry.cpp:40): registered operation GetConfiguration
21:43:24.319 -> [MO] debug (OperationRegistry.cpp:40): registered operation RemoteStartTransaction
21:43:24.319 -> [MO] debug (OperationRegistry.cpp:40): registered operation RemoteStopTransaction
21:43:24.319 -> [MO] debug (OperationRegistry.cpp:40): registered operation Reset
21:43:24.319 -> [MO] debug (OperationRegistry.cpp:40): registered operation TriggerMessage
21:43:24.319 -> [MO] debug (OperationRegistry.cpp:40): registered operation UnlockConnector
21:43:24.366 -> [MO] debug (OperationRegistry.cpp:40): registered operation Authorize
21:43:24.366 -> [MO] debug (OperationRegistry.cpp:40): registered operation StartTransaction
21:43:24.366 -> [MO] debug (OperationRegistry.cpp:40): registered operation StatusNotification
21:43:24.366 -> [MO] debug (OperationRegistry.cpp:40): registered operation StopTransaction
21:43:24.366 -> [MO] debug (Configuration.cpp:70): init new configurations container: /client-state.jsn
21:43:24.413 -> [MO] debug (TransactionStore.cpp:84): 0-99999 does not exist
21:43:24.413 -> [MO] debug (TransactionStore.cpp:84): 1-99999 does not exist
21:43:24.413 -> [MO] debug (OperationRegistry.cpp:40): registered operation Heartbeat
21:43:24.413 -> [MO] debug (OperationRegistry.cpp:40): registered operation GetLocalListVersion
21:43:24.413 -> [MO] debug (OperationRegistry.cpp:40): registered operation SendLocalList
21:43:24.413 -> [MO] debug (AuthorizationService.cpp:51): no local authorization list stored already
21:43:24.413 -> [MO] debug (Configuration.cpp:70): init new configurations container: /reservations.jsn
21:43:24.458 -> [MO] debug (OperationRegistry.cpp:40): registered operation CancelReservation
21:43:24.458 -> [MO] debug (OperationRegistry.cpp:40): registered operation ReserveNow
21:43:24.458 -> [MO] debug (OperationRegistry.cpp:40): registered operation Reset
21:43:24.458 -> [MO] debug (OperationRegistry.cpp:40): registered operation UpdateFirmware
21:43:24.458 -> [MO] debug (OperationRegistry.cpp:40): registered operation FirmwareStatusNotification
21:43:24.458 -> [MO] debug (OperationRegistry.cpp:40): registered operation GetDiagnostics
21:43:24.458 -> [MO] debug (OperationRegistry.cpp:40): registered operation DiagnosticsStatusNotification
21:43:24.505 -> [MO] debug (FilesystemAdapter.cpp:143): File open successful: /ocpp-config.jsn
21:43:24.505 -> [MO] debug (FilesystemUtils.cpp:73): Loaded JSON file: /ocpp-config.jsn
21:43:24.505 -> [MO] debug (ConfigurationContainerFlash.cpp:190): Initialization finished
21:43:24.552 -> [MO] debug (FilesystemAdapter.cpp:143): File open successful: /client-state.jsn
21:43:24.552 -> [MO] debug (FilesystemUtils.cpp:73): Loaded JSON file: /client-state.jsn
21:43:24.552 -> [MO] debug (ConfigurationContainerFlash.cpp:190): Initialization finished
21:43:24.598 -> [MO] debug (FilesystemAdapter.cpp:143): File open successful: /reservations.jsn
21:43:24.598 -> [MO] debug (FilesystemUtils.cpp:73): Loaded JSON file: /reservations.jsn
21:43:24.598 -> [MO] debug (ConfigurationContainerFlash.cpp:190): Initialization finished
21:43:24.598 -> [MO] info (MicroOcpp.cpp:290): initialized MicroOcpp v1.0.0

**Comment by feyzanoz** [comment]
hi  @FlxMojojojo is there any progress? I'm stuck at this stage as well. Have you made any changes to the code, like in TinyGSM

**Comment by FlxMojojojo** [comment]
@feyzanoz We have resolved the issue, Dont use software serial, Use only hardware serial for communication and it will work. 

What i mean is use the hardware serial on ESP32 to SIM 800.

**Comment by feyzanoz** [comment]
I'm using hardware serial. If I don't change anything in TinyGSM, it doesn't even write "disconnected." Instead of the waitresponse part in TinyGSM, I added a delay. This time, it said "Disconnected" in the serial monitor. Did you change anything in the code other than hardware serial?

**Comment by feyzanoz** [comment]
I was using the ESP32 S3 WROOM-1 board. I converted the default Serial2 defined in the code to Serial1. I also set the rx pin to 18 and the tx pin to 17 by making it serial1 in the code. This way, I was able to communicate with SteVe. Thank you again. @ziyadtarek7, @FlxMojojojo

**Comment by FlxMojojojo** [comment]
Good to know you resolved it. However we need work towards solving this on software serial.

**Comment by feyzanoz** [comment]
I will look into this matter. Since I need to progress quickly, for now, I am continuing with hardware serial. How do you use tests for OCPP?
